spring:
  application:
    name: danafix-product
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgresql-container:5432/public
    username: postgres
    password: dicky123
  jpa:
    show-sql: true