spring:
  application:
    name: danafix-individual
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: dicky123
  jpa:
    show-sql: true